### ISSUE TITLE
Report file compilation time

### ISSUE THREAD

**Issue by delannoyk** [giginet/xcprofiler#19]
Hi @giginet 

Thanks for this! I've been trying to set it up with your danger plugin and it looks promising!

I was wondering if there was a way to add a threshold for files instead of function bodies and maybe to report the compilation time on the whole file?

**Comment by giginet** [comment]
Hi @delannoyk thanks for using xcprofiler 😄

In default, you can't profile build times per files.
However, you can implement custom reporter to gather and groups logs.

```ruby
require 'xcprofiler'

results = {}
profiler = Xcprofiler::Profiler.by_product_name("MyApp")
profiler.reporters = [
    Xcprofiler::BlockReporter.new do |executions|
        results = executions.group_by { |execution| execution.filename }.map { |file, executions| [file, executions.sum { |e| e.time }] }.to_h
    end
]
profiler.report!
puts results
```

How about this solution?

**Comment by delannoyk** [comment]
Perfect, thanks!
