### ISSUE TITLE
Command line option for output format

### ISSUE THREAD

**Issue by richellis** [giginet/xcprofiler#20]
It would be great to be able to specify the JSON reporter format as a command-line option, e.g.
```
xcprofiler MyApp --output-json MyApp-xcprofile.json
```
I think this would allow for easier integration with continuous integration scripts.

Thanks for an awesome project!

**Comment by giginet** [comment]
Hi @richellis. Thanks for your feedback.

For example, in [xcpretty](https://github.com/supermarin/xcpretty), we can set formatter from command line options.
I'll refer to it and consider about this feature.

Until that please implement a wrapper script to set formatter.

**Comment by giginet** [comment]
I'm working on.
