### ISSUE TITLE
"Zlib::GzipFile::Error: [!] unexpected end of file"

### ISSUE THREAD

**Issue by ainame** [giginet/xcprofiler#29]
Xcode: 9.0 (9A235)
version: v0.6.2

> Zlib::GzipFile::Error: [!] unexpected end of file
https://github.com/giginet/xcprofiler/blob/a817a517b7620ca3ab0c4dc4063f1a259c73c7d9/lib/xcprofiler/derived_data.rb#L66

We had this error occasionally on our CI server.
Is there any latest Xcode related problem?

Or should this library handle this kind of error as library error?

```ruby
class Xcprofiler::Error < StandardError; end

begin
  Zlib::GzipReader.open(@path) do |gz|
    @lines = gz.read.split(/\r/)
  end
rescue => e
  raise Xcprofiler::Error.new(e)
end
```

**Comment by giginet** [comment]
🙏

**Comment by ainame** [comment]
I'll just close this issue. We have been disabling xcprofiler in our project so I can't tell if this is still a problem any more 🙏
